### ISSUE TITLE
Incorrect FR_FIXMUL32u

### ISSUE THREAD

**Issue by dwilliss** [deftio/fr_math#1]
I was trying to use this to write a fixed-point mandelbrot set program to run on a GPU using the CUDA Toolkit.  The results were interesting but wrong.

![image](https://user-images.githubusercontent.com/1755696/111035337-a1c63800-83df-11eb-9712-4352ae29dc82.png)

Zooming in on that dot in the center gives this cool image:
![image](https://user-images.githubusercontent.com/1755696/111035435-2f098c80-83e0-11eb-8f5d-79e75d8d748b.png)

Anyway, the culpret turned out to be that the 4th term needed a right shift by 16

```
#define FR_FIXMUL32u(x,y)	(					\
	(((x>>16)*(y>>16))<<16)+					\
	((x>>16)*(y&0xffff))+						\
	((y>>16)*(x&0xffff))+						\
	((((x&0xffff)*(y&0xffff)))>>16)					\
	)

```
After that, everything looked correct.
![image](https://user-images.githubusercontent.com/1755696/111035563-b951f080-83e0-11eb-9d90-f3b87fa3dbc9.png)

This was with 15.16 fixed.  Since the magnitude of the numbers is so low, I tried 4.27 hoping to get better precision as I zoomed in.  Instead I got this.
![image](https://user-images.githubusercontent.com/1755696/111035762-86f4c300-83e1-11eb-9e33-7b874332818c.png)
I'm not sure what's wrong here yet, but if I zoom in 1200x on that right circle...
![image](https://user-images.githubusercontent.com/1755696/111035843-e521a600-83e1-11eb-81bf-3bf0106c5017.png)

**Comment by deftio** [comment]
Ok I'll take a look!

**Comment by dwilliss** [comment]
FYI, I did some math and trying to multiply this way with .27 just causes the first term to overflow.  But for .16 numbers it works great.

I came up with a nice optimization for squaring a number.  You only have to take the ABS once and you can ignore the sign of the output since it will always be positive.

```
// Square can be simplified since it's one number and the result must be positive
__device__ inline int FR_Square(int x) {
	x = FR_ABS(x);
	return FR_FIXMUL32u(x, x);
}
```

**Comment by deftio** [comment]
OK good find.  I updated the FR_FIXMUL32 macro.

I added FR_SQUARE but as a macro.  The reason for that instead of inline, is there is an old project on an embedded system that is using C99 support.  This should give the same effect though.

Much thanks for your contribution!
